<?$this->display('inc.header.phtml');?>
<div id="wrap">
	<div id="cols">
		<div id="left">
			<div class="meniu-lateral">
				<ul>
					<li><a href="">News</a></li>
					<li class="google"><a href="">Google+</a></li>
					<li class="twitter"><a href="">Twitter</a></li>
					<li class="facebook"><a href="">Facebook</a></li>
				</ul>
			</div>
		</div>
		<div id="right">
			<form action="home/filter">
				<div id="filterForm" style="font-size:12px;margin-bottom:15px;">
					<input style="width: 99%;" placeholder="filter..." type="text" name="search" /><br />
				</div>
			</form>
			
			<? foreach ($items as $item): ?>
			<div class="item">
				<div class="hr"></div>
				<div style="float: right;">
					<span title="<?=date('d.m.Y h:i:s', strtotime($item->timestamp))?>"><?=humanizeDateDiffference(time(), strtotime($item->timestamp))?></span>
				</div>
				<span class="img">
					<?
					$image = 'http://graph.facebook.com/1/picture';
					if (isset($item->author_data['avatar'])) 
						$image = $item->author_data['avatar'];
					$link = 'https://www.facebook.com';
					if (!empty($item->link))
						$link = $item->link;
					?>
					<img src="<?=$image?>" width="50" height="50"/>
				</span>
				<span class="name"><?=ehtml($item->author)?></span>
				<span class="via"><a href="<?=ehtml($link)?>">via <?=ucfirst($item->service)?></a></span>
				<p class="content">
					<?=nl2br(ehtml($item->content))?>
				</p>
				<br style="clear:both;height:0px;"/>
			</div>
			<? endforeach; ?>
			
		</div>
		<br style="clear:both;">
	</div>
</div>
<?$this->display('inc.footer.phtml');?>