<!DOCTYPE html>
<html>
	<head>
		<title>Simplify</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="">
		<meta name="author" content="">
		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
		<link href="css/stylesheet.css" rel="stylesheet">
	</head>
	<body>
		<div id="nav-container">
			<div id="navbar">
				<span style="float:left;"><a href="home"><img src="img/logo.png"/></a></span>
				<span style="float:left;margin-top:21px;font-size:11px;">Hello, we present to you, Simplify!</span>
				<div id="user">
					<ul id="menu">
					    <li>
					    	<a href="home"><strong><?=$user['name']?></strong></a>
					        <ul>
					            <li><a href="connect-your-accounts">Connect your accounts</a></li>
					            <li><a href="settings">Settings</a></li>
					            <li><a href="login?logout" style="border-bottom: 1px solid #EEE;">Logout</a></li>
					        </ul>
					    </li>
					</ul>
				</div>
				<br style="clear:both;height:0px;"/>
			</div>
		</div>