<!DOCTYPE html>
<html>
	<head>
		<title>Simplify</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="">
		<meta name="author" content="">
		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
		<link href="css/stylesheet.css" rel="stylesheet">
	</head>
	<body>
		<div id="nav-container">
			<div id="navbar">
				<span style="float:left;"><a href="home"><img src="img/logo.png"/></a></span>
				<span style="float:left;margin-top:21px;font-size:11px;">Hello, we present to you, Simplify!</span>
				<br style="clear:both;height:0px;"/>
			</div>
		</div>
		<div id="wrap">
			<div id="cols" style="border-bottom:1px solid #eeeeee;padding-bottom:50px;padding-top: 100px;">
				<? if (isset($error)): ?><div class="error">
					<?=$error;?>
				</div><br /><? endif; ?>
				<div style="270px;float:left;">
					<h3>Login</h3>
					<form action="login/login" method="post">
						<table>
							<tr>
								<td>email &nbsp;</td>
								<td><input type="text" name="email" id="email"/></td>
							</tr>
							<tr>
								<td>password &nbsp;</td>
								<td><input type="password" name="password" id="password"/></td>
							</tr>
							<tr>
								<td></td>
								<td><input type="submit"/></td>
							</tr>
						</table>
					</form>
				</div>
				<div style="float:left;width:480px;margin-left:50px;">
					<h3>Register</h3>
					<form action="login/register" method="post">
						<table>
							<tr>
								<td>name &nbsp;</td>
								<td><input type="text" name="name" id="name"/></td>
							</tr>
							<tr>
								<td>email &nbsp;</td>
								<td><input type="text" name="email" id="email"/></td>
							</tr>
							<tr>
								<td>password</td>
								<td><input type="password" name="password" id="password"/></td>
							</tr>
							<tr>
								<td>repeat</td>
								<td><input type="password" name="password2" id="password2"/></td>
							</tr>
							<tr>
								<td></td>
								<td><input type="submit" value="Create Account"/></td>
							</tr>
						</table>
					</form>
				</div>
				<br style="clear:both;">
			</div>
		</div>


		<script src="http://code.jquery.com/jquery-latest.js"></script>
	</body>
</html>