		<div id="wrap">
			<h2>User details</h2>
			<form action="" method="post">
				<table>
					<tr>
						<td>Full name</td>
						<td><input type="text"/></td>
					</tr>
					<tr>
						<td>Email adress</td>
						<td><input type="text"/></td>
					</tr>
					<tr>
						<td></td>
						<td><input type="submit"/></td>
					</tr>
				</table>
			</form>
			<h2>Change your password</h2>
			<form action="" method="post">
				<table>
					<tr>
						<td>Old password</td>
						<td><input type="text"/></td>
					</tr>
					<tr>
						<td>New password</td>
						<td><input type="text"/></td>
					</tr>
					<tr>
						<td>Rewrite new password</td>
						<td><input type="text"/></td>
					</tr>
					<tr>
						<td></td>
						<td><input type="submit"/></td>
					</tr>
				</table>
			</form>
		</div>